create database SaludPaillaco_bddd

use SaludPaillaco_bddd


select * from app_saludpaillaco_RegistroPdfAsistencia


SELECT * FROM app_saludpaillaco_Asistencia LIMIT 1000000;

SHOW VARIABLES LIKE 'max_allowed_packet';


DELETE FROM auth_user WHERE id = (SELECT user_id FROM app_saludpaillaco_perfilusuario WHERE rut = '172968023');

SET SQL_SAFE_UPDATES = 0;


ALTER TABLE app_saludpaillaco_AsistenciaMes
MODIFY COLUMN mes VARCHAR(20);



SELECT 
    a.*, 
    p.*
FROM 
    app_saludpaillaco_asistenciames AS a
JOIN 
    app_saludpaillaco_perfilusuario AS p
    ON a.perfil_id = p.id;

SELECT * 
FROM auth_user u
JOIN app_saludpaillaco_perfilusuario p
ON u.id = p.user_id;

INSERT INTO App_SaludPaillaco_profesion_oficio(id, profesion_oficio)
VALUES
    (1, 'ENFERMERA'),
    (2, 'AUXILIAR'),
    (3, 'TENS'),
    (4, 'ADMINISTRATIVO'),
    (5, 'TEC. EN ENFERMERIA'),
    (6, 'TECNOLOGO MEDICO'),
    (7, 'MATRON'),
    (8, 'TEC. ENFERMERIA NIVEL SUPERIOR'),
    (9, 'MATRONA'),
    (10, 'NUTRICIONISTA'),
    (11, 'CIRUJANO DENTISTA'),
    (12, 'PROFESOR EDUCACION FISICA'),
    (13, 'ASISTENTE SOCIAL'),
    (14, 'APOYO PROFESIONAL, UNIDAD DE PLANES Y PROGRAMAS'),
    (15, 'ADMINISTRATIVA'),
    (16, 'AUXILIAR DE SERVICIO'),
    (17, 'TERAPEUTA OCUPACIONAL'),
    (18, 'FONOAUDIOLOGA'),
    (19, 'KINESIOLOGA'),
    (20, 'MEDICO CIRUJANO'),
    (21, 'TECNICO EN PODOLOGIA CLINICA'),
    (22, 'TRABAJADORA SOCIAL'),
    (23, 'TECNICO NIVEL SUPERIOR EN FARMACIA'),
    (24, 'TONS'),
    (25, 'CONDUCTOR'),
    (26, 'TECNOLOGO MEDICO EN OFTALMOLOGIA'),
    (27, 'ODONTOLOGA'),
    (28, 'ASISTENTE DENTAL'),
    (29, 'PSICOLOGO'),
    (30, 'KINESIOLOGO'),
    (31, 'TECNICO DENTAL'),
    (32, 'GUARDIA DE SEGURIDAD'),
    (33, 'AUXILIAR DE SERVICIO Y CONDUCTOR'),
    (34, 'ABOGADO'),
    (35, 'INGENIERA CONTROL DE GESTION'),
    (36, 'APOYO ADQUISICIONES'),
    (37, 'TECNICO EN TELECOMUNICACIONES CONECTIVIDAD Y REDES'),
    (38, 'PSICOLOGA'),
    (39, 'MEDICO'),
    (40, 'TECNICO JURIDICO'),
    (41, 'PODOLOGA'),
    (42, 'PERIODISTA'),
    (43, 'LABORATORISTA DENTAL'),
    (44, 'INGIENIERO ADMINISTRACION PUBLICA'),
    (45, 'ACUPUNTURISTA'),
    (46, 'PSICOPEDAGOGA ED DIFERENCIAL'),
    (47, 'ADMINISTRA'),
    (48, 'INGENIERA EN ADM DE EMPRESAS'),
    (49, 'QUIMICO FARMA'),
    (50, 'TECNICO EN ENFERMERIA NIVEL SUPERIOR'),
    (51, 'SECRETARIA ADMINISTRATIVA'),
    (52, 'INGENIERO EN ADMINISTRACION'),
    (53, 'TECNICO JURIDICO ADMINISTRATIVO'),
    (54, 'AUXILIAR DE ASEO'),
    (55, 'TECNICO EN TRABAJO SOCIAL'),
    (56, 'PSICOPEDAGOGA'),
    (57, 'ORTODONCISTA'),
    (58, 'INGENIERO DE EJECUCION EN ADMINISTRACION'),
    (59, 'JEFA DE FINANZAS'),
    (60, 'PROFESORA'),
    (61, 'TECNICO ENFERMERIA'),
    (62, 'TECNICO EN FARMACIA A NIVEL SUPERIOR'),
    (63, 'EDUCADORA DIFERENCIAL'),
    (64, 'INFORMATICA'),
    (65, 'TRABAJADOR PUBLICO'),
    (66, 'TECNICO EN ENFERMERIA DE NIVEL SUPERIOR'),
    (67, 'PROGRAMADOR ANALISTA'),
    (68, 'SOLDADOR'),
    (69, 'ODONTOLOGO'),
    (70, 'PSICOPEDAGOGA'),
    (71, 'TELECOMUNICACIONES');
    
DROP DATABASE SaludPaillaco_bddd

