# Generated by Django 5.0 on 2025-01-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0002_alter_profesion_oficio_profesion_oficio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
