# Generated by Django 5.0 on 2025-01-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0004_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
