# Generated by Django 5.0 on 2025-01-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0005_perfilusuario_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='numero_espera',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
