# Generated by Django 5.0 on 2025-01-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0008_registrocambios_delete_cambioregistro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroCambios',
        ),
    ]
