# Generated by Django 5.0 on 2025-01-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0010_registrocambios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroCambios',
        ),
    ]
