# Generated by Django 5.0 on 2025-01-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0012_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pdf_asistencia',
            field=models.FileField(blank=True, null=True, upload_to='asistencias_pdfs/'),
        ),
    ]
