# Generated by Django 5.0 on 2025-01-24 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0013_perfilusuario_pdf_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('año', models.IntegerField(default=2025)),
                ('pdf_asistencia', models.FileField(blank=True, null=True, upload_to='asistencias_pdfs/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='App_SaludPaillaco.perfilusuario')),
            ],
            options={
                'unique_together': {('perfil', 'mes', 'año')},
            },
        ),
    ]
