# Generated by Django 5.0 on 2025-01-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0014_asistenciames'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoSubido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_excel', models.FileField(upload_to='excels/')),
                ('plantilla_pdf', models.FileField(upload_to='plantillas/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDFGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(upload_to='pdfs/')),
                ('ac', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('dpto', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
