# Generated by Django 5.0 on 2025-01-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0015_archivosubido_pdfgenerado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivoSubido',
        ),
        migrations.DeleteModel(
            name='PDFGenerado',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='horas_trabajadas',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='perfil',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='ano',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistencia',
            name='dpto',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistencia',
            name='marcaciones',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistencia',
            name='mes',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistencia',
            name='nombre',
            field=models.CharField(default=5, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='rut',
            field=models.CharField(default=10, max_length=12),
            preserve_default=False,
        ),
    ]
