# Generated by Django 5.0 on 2025-01-25 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0017_asistenciaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='ac',
            field=models.CharField(default=20, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistencia',
            name='perfil',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='App_SaludPaillaco.perfilusuario'),
            preserve_default=False,
        ),
    ]
