# Generated by Django 5.0 on 2025-01-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0018_asistencia_ac_asistencia_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='perfil',
        ),
    ]
