# Generated by Django 5.0 on 2025-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0019_remove_asistencia_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='ac',
            field=models.CharField(max_length=100),
        ),
    ]
