# Generated by Django 5.0 on 2025-01-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0021_alter_asistencia_ac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='ac',
            field=models.CharField(max_length=100),
        ),
    ]
