# Generated by Django 5.0 on 2025-01-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0022_alter_asistencia_ac'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_funcionario', models.CharField(max_length=12)),
                ('mes', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('rut_funcionario', 'mes', 'ano')},
            },
        ),
    ]
