# Generated by Django 5.0 on 2025-01-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0023_pdfgenerado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PdfGenerado',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='pdf_generado',
            field=models.BooleanField(default=False),
        ),
    ]
