# Generated by Django 5.0 on 2025-01-26 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0024_delete_pdfgenerado_asistencia_pdf_generado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='pdf_generado',
        ),
    ]
