# Generated by Django 5.0 on 2025-01-26 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0025_remove_asistencia_pdf_generado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistenciames',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='asistenciames',
            name='perfil',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='perfil_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_SaludPaillaco.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.DeleteModel(
            name='Asistenciaa',
        ),
        migrations.DeleteModel(
            name='AsistenciaMes',
        ),
    ]
