# Generated by Django 5.0 on 2025-01-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0026_alter_asistenciames_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='perfil_usuario',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
