# Generated by Django 5.0 on 2025-01-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0027_remove_asistencia_perfil_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='pdf_asistencia',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='pdf_asistencia',
            field=models.FileField(blank=True, null=True, upload_to='asistencias_pdfs/'),
        ),
    ]
