# Generated by Django 5.0 on 2025-01-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0028_remove_perfilusuario_pdf_asistencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='pdfs/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
