# Generated by Django 5.0 on 2025-01-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0032_remove_asistencia_pdf_asistencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutEnInvernacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('pdf_asistencia', models.FileField(blank=True, null=True, upload_to='pdf_invernacion/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PdfDocumento',
        ),
    ]
