# Generated by Django 5.0 on 2025-01-27 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0033_ruteninvernacion_delete_pdfdocumento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RutEnInvernacion',
        ),
    ]
