# Generated by Django 5.0 on 2025-01-28 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0034_delete_ruteninvernacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPdfAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(upload_to='registros_pdfs/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_pdf', to='App_SaludPaillaco.perfilusuario')),
            ],
        ),
    ]
