# Generated by Django 5.0 on 2025-02-04 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SaludPaillaco', '0036_remove_perfilusuario_año_asistencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(upload_to='asistencias_pdfs/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('mes_asistencia', models.CharField(blank=True, max_length=20, null=True)),
                ('ano_asistencia', models.IntegerField(blank=True, null=True)),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_pdfs', to='App_SaludPaillaco.perfilusuario')),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroPdfAsistencia',
        ),
    ]
